# Generated by Django 2.2.19 on 2022-05-09 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220509_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_linked', to='groups.Group'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
